version: '3'

services:
  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ../:/var/www/html
    ports:
      - "9000:9000"
    environment:
      - COMPOSE_PROJECT_NAME

  nginx:
    build:
      context: ./nginx
    restart: always
    volumes:
      - ../:/var/www/html/
    depends_on:
      - php-fpm
    ports:
      - "8080:8080"
    environment:
      - COMPOSE_PROJECT_NAME